"set fuoptions=maxvert,maxhorz
"set guifont=Monaco:h12
set guifont="DejaVu Sans Mono":h10
set vb t_vb= " Cause when the GUI starts, 't_vb' is reset to its default value

" Mac *************************************************************************
if has("mac") 
  set imd
endif
