"set fuoptions=maxvert,maxhorz
set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
set vb t_vb= " Cause when the GUI starts, 't_vb' is reset to its default value

" Mac *************************************************************************
if has("mac") 
  set imd
  set guifont=Monaco:h12
endif

let g:syntastic_mode_map={ 'mode': 'active',
                     \ 'active_filetypes': ['ruby'],
                     \ 'passive_filetypes': ['haml'] }
