"set fuoptions=maxvert,maxhorz

set guifont=Monaco:h12

set vb t_vb= " Cause when the GUI starts, 't_vb' is reset to its default value

" Mac *************************************************************************
if has("mac")
  set imd
endif

let g:syntastic_mode_map={ 'mode': 'active',
                     \ 'active_filetypes': ['ruby'],
                     \ 'passive_filetypes': ['haml'] }
