source /etc/profile
source $HOME/.bash_profile
source $HOME/.bashrc
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

# load zsh locale
source $HOME/github/mvj3/utils/zsh/env.zsh

# load zsh aliases
source $HOME/github/mvj3/utils/zsh/aliases.zsh

# terminal highlight
# brew install grc # 用colourify包装了很多命令，比如 colourify gcc
source $(brew --prefix)/etc/grc.bashrc

# brew install nvm
#source $(brew --prefix nvm)/nvm.sh

# pyenv
export PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache
export PYTHON_BUILD_CACHE_PATH=$HOME/.pyenv_download_cache
export PYENV_ROOT="$HOME/.pyenv"
export PYENV_VERSION=2.7.9
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

plugins=(
# http://superuser.com/questions/236953/zsh-starts-incredibly-slowly
  git gitfast git-extras git-flow gitignore github
  mercurial
  pip fabric virtualenv pylint
  ruby rvm bundler
  systemadmin osx screen docker
  brew-cask brew
  node nvm bower
  last-working-dir per-directory-history
  web-search
  vi-mode common-aliases terminalapp
  colorize colored-man
)


[[ -s "/usr/local/opt/autoenv/activate.sh" ]] && source "/usr/local/opt/autoenv/activate.sh"


function check() { ruby -e 'loop { sleep 600; puts Time.now; `open http://have-a-break` }' }
alias gD="git diff --cached"
alias kernprof="/usr/local/var/lib/pyenv/versions/2.7.5//bin/kernprof.py -l -v"
export HADOOP_HOME="/usr/local/Cellar/hadoop/2.5.1/libexec/etc/hadoop"

export GOPATH="$HOME/golang-workspace"
